security:
    providers:
        fos_user_provider:
            id: fos_user.user_manager
    firewalls:
        main:
            form_login:
                provider:                       fos_user_provider
                login_path:                     /login
                check_path:                     /login-check
            logout: true
            anonymous: true
    access_control:
        - { path: "/dashboard.*", role: IS_AUTHENTICATED_FULLY }
        - { path: "/.*", role: IS_AUTHENTICATED_ANONYMOUSLY }

fos_user:
    db_driver: mongodb
    provider_key: main
    encoder:
        iterations: 1
        encode_as_base64: false
        algorithm: sha1
    class:
        model:
            user: Application\UserBundle\Document\User
            group: FOS\UserBundle\Document\DefaultGroup

