security:
    #encoders:
    #    Symfony\Component\Security\Core\User\User: plaintext
    encoders:
        "FOS\UserBundle\Model\UserInterface":
            iterations: 1
            encode_as_base64: false
            algorithm: sha1

    providers:
        fos_user_provider:
            id: fos_user.user_provider.username

    firewalls:
        main:
            form_login:
                provider:   fos_user_provider
                check_path: /login_check
                login_path: /login
            logout:     true
            anonymous:  true

    access_control:
        - { path: "/admin/*", role: IS_AUTHENTICATED_FULLY }
        - { path: "/.*", role: IS_AUTHENTICATED_ANONYMOUSLY }
