<?php
/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Vespolina\ProductBundle\Document;

use Vespolina\ProductBundle\Document\BaseProduct as BaseProduct;

/**
 * This file has been generated by the EasyExtends bundle ( http://sonata-project.org/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/docs/mongodb_odm/1.0/en/reference/working-with-objects.html
 *
 * @author Luis Cordova <cordoval@gmail.com>
 */
class DownloadableProduct extends BaseProduct
{

    /**
     * @var integer $id
     */
    protected $id;

    /**
     * @var string $pdfFilePath
     */
    protected $pdfFilePath;

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
      return $this->id;
    }

    /**
     * Get $pdfFilePath
     *
     * @return string $pdfFilePath
     */
    public function getPdfFilePath()
    {
       return $this->pdfFilePath;
    }

    /**
     * Set $pdfFilePath
     *
     * @param string $pdfFilePath
     */
    public function setPdfFilePath($pdfFilePath)
    {
       $this->pdfFilePath = $pdfFilePath;
    }

    /**
     * @var string $id
     */
    protected $price;

    /**
     * Get $price
     *
     * @return string $price
     */
    public function getPrice()
    {
      return $this->price;
    }

    /**
     * Set $price
     */
    public function setPrice($price)
    {
      $this->price = $price;
    }


}